import type { Metadata } from 'next';
import { geistMono, geistSans } from '@ui/font';

import '../styles/globals.css';

export const metadata: Metadata = {
  title: {
    template: '%s · Bartosz Szkolnik',
    default: 'Bartosz Szkolnik',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>{children}</body>
    </html>
  );
}
